repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: tmp
        args: [--config=./pyproject.toml]
  - repo: local
    hooks:
      - id: clear_notebooks
        name: clear_notebooks
        entry: python -m tmp.clear_notebooks
        language: system
        verbose: true
        types: [jupyter]
